config/routes.rb
Rails.application.routes.draw do

  get "print_images/user_index", to: "print_images#user_index", as: "print_images_user_index"
  # post "print_images/user_index", to: "print_images#user_index", as: "print_images_user_index"
  get "print_images/user_show/:id", to: "print_images#user_show", as: "print_images_user_show"
  get "single_posts/user_index" => "single_posts#user_index"
  get "single_posts/user_show/:id", to: "single_posts#user_show", as: "single_posts_user_show"

  resources :single_posts
  resources :print_images

  resources :print_images do
    member do
      get :download
    end
  end

  resources :events
  resources :categories
  root :to => "core_pages#top"
  get 'core_pages/top'
  #resources :form_answers
  resources :admins
  get "admin_users" => "admins#admin_users"
  get "admin_questions" =>"admins#admin_questions"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    #root :to => "devis/sessions#new"
  end
 get "users/:id" => "admins#show"
 get "users/:id/posts" => "admins#your_posts", as: "your_posts"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #namespace :administrator do
    #resources :users, only: [:index]
  # end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/admin_questions.html.erb
<h1>
    管理者専用画面
</h1>
<h1>
    質問一覧
</h1>

<div class="container">
    <% @users_questions.each do |users_question| %>
        <div class="<%= table_row %>">
            <div class="col-1 text-center <%= table_col %>"><%= users_question.user_id %></div>
            <div class="col-3 text-center <%= table_col %>"><%= users_question.subject_form_question %></div>
            <div class="col-4 text-center <%= table_col %>"><%= users_question.content_form_question %></div>
            <div class="col-2 text-center <%= table_col %>"><%= users_question.created_at %></div>
        
        </div>
    <% end %>
</div>

app/views/admins/admin_users.html.erb
<h1>
    管理者専用画面
</h1>
<h1>
    ユーザー一覧
</h1>

<div class= "container">
    <% @users.each do |user| %>
        <div class="<%= table_row %>">
            <div class="col-1 text-center <%= table_col %>"><%= user.id %></div>
            <div class="col-2 <%= table_col %>"><%= user.email %></div>
            <% if user.admin == true %>
                <div class="col-2 <%= table_col %>"><%= user.admin %></div>
            <% else %>
                <div class="col-2 <%= table_col %>">無し</div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1 class="text-center my-4">管理者専用画面</h1>

<div class="container text-center">
  <div class="row justify-content-center">
    <!-- 印刷テンプレートリンク -->
    <div class="col-md-4 mb-3">
      <%= link_to "印刷テンプレート", print_images_path, class: "btn btn-primary btn-lg btn-block shadow" %>
    </div>

    <!-- 単発おもちゃリンク -->
    <div class="col-md-4 mb-3">
      <%= link_to "単発おもちゃ", single_posts_path, class: "btn btn-success btn-lg btn-block shadow" %>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<h1> マイページ </h1>
<%= @user.id %>

app/views/admins/your_posts.html.erb
<h1> マイページ </h1>
<h1> あなたの投稿 </h1>
<% @posts.each do |post| %>
    <%= post.subject_form_question %>
    <%= post.content_form_question %>
<% end %>