config/routes.rb
Rails.application.routes.draw do

  get "print_images/user_index", to: "print_images#user_index", as: "print_images_user_index"
  # post "print_images/user_index", to: "print_images#user_index", as: "print_images_user_index"
  get "print_images/user_show/:id", to: "print_images#user_show", as: "print_images_user_show"
  get "single_posts/user_index" => "single_posts#user_index"
  get "single_posts/user_show/:id", to: "single_posts#user_show", as: "single_posts_user_show"

  resources :single_posts
  resources :print_images

  resources :print_images do
    member do
      get :download
    end
  end

  resources :events
  resources :categories
  root :to => "core_pages#top"
  get 'core_pages/top'
  #resources :form_answers
  resources :admins
  get "admin_users" => "admins#admin_users"
  get "admin_questions" =>"admins#admin_questions"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    #root :to => "devis/sessions#new"
  end
 get "users/:id" => "admins#show"
 get "users/:id/posts" => "admins#your_posts", as: "your_posts"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #namespace :administrator do
    #resources :users, only: [:index]
  # end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/single_post.rb
class SinglePost < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :event
end

app/controllers/single_posts_controller.rb
class SinglePostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ index show new edit create update destroy ]
  before_action :set_single_post, only: %i[ show edit update destroy ]

  # GET /single_posts or /single_posts.json
  def index
    @single_posts = SinglePost.all
  end

  def user_index
    @single_posts = SinglePost.all
  end

  # GET /single_posts/1 or /single_posts/1.json
  def show
  end

  def user_show
    @single_post = SinglePost.find(params[:id])
  end


  # GET /single_posts/new
  def new
    @single_post = SinglePost.new
  end

  # GET /single_posts/1/edit
  def edit
  end

  # POST /single_posts or /single_posts.json
  def create
    @single_post = SinglePost.new(single_post_params)

    respond_to do |format|
      if @single_post.save
        format.html { redirect_to @single_post, notice: "Single post was successfully created." }
        format.json { render :show, status: :created, location: @single_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @single_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /single_posts/1 or /single_posts/1.json
  def update
    respond_to do |format|
      if @single_post.update(single_post_params)
        format.html { redirect_to @single_post, notice: "Single post was successfully updated." }
        format.json { render :show, status: :ok, location: @single_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @single_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /single_posts/1 or /single_posts/1.json
  def destroy
    @single_post.destroy

    respond_to do |format|
      format.html { redirect_to single_posts_path, status: :see_other, notice: "Single post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_single_post
      @single_post = SinglePost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def single_post_params
      params.require(:single_post).permit(:single_post_image, :user_id, :category_id, :event_id, :name, :subject, :content)
    end
end

app/views/single_posts/_form.html.erb
<%= form_with(model: single_post) do |form| %>
  <% if single_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(single_post.errors.count, "error") %> prohibited this single_post from being saved:</h2>

      <ul>
        <% single_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :single_post_image %>
    <%= form.text_area :single_post_image %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/single_posts/edit.html.erb
<h1>Editing Single Post</h1>

<%= render 'form', single_post: @single_post %>

<%= link_to 'Show', @single_post %> |
<%= link_to 'Back', single_posts_path %>

app/views/single_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>admin用のSingle Posts indexページ</h1>

<table>
  <thead>
    <tr>
      <th>Single post image</th>
      <th>User</th>
      <th>Category</th>
      <th>Event</th>
      <th>Name</th>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @single_posts.each do |single_post| %>
      <tr>
        <td><%= single_post.single_post_image %></td>
        <td><%= single_post.user_id %></td>
        <td><%= single_post.category_id %></td>
        <td><%= single_post.event_id %></td>
        <td><%= single_post.name %></td>
        <td><%= single_post.subject %></td>
        <td><%= single_post.content %></td>
        <td><%= link_to 'Show', single_post %></td>
        <td><%= link_to 'Edit', edit_single_post_path(single_post) %></td>
        <td><%= link_to 'Destroy', single_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Single Post', new_single_post_path %>

アドミン用

app/views/single_posts/new.html.erb
<h1>New Single Post</h1>

<%= render 'form', single_post: @single_post %>

<%= link_to 'Back', single_posts_path %>

app/views/single_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Single post image:</strong>
  <%= @single_post.single_post_image %>
</p>

<p>
  <strong>User:</strong>
  <%= @single_post.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @single_post.category_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @single_post.event_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @single_post.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @single_post.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @single_post.content %>
</p>

<%= link_to 'Edit', edit_single_post_path(@single_post) %> |
<%= link_to 'Back', single_posts_path %>

app/views/single_posts/user_index.html.erb
ユーザーが見る単発おもちゃindex


<% @single_posts.each do |single_post| %>
    <tr>
      <td><%= single_post.single_post_image %></td>
      <td><%= single_post.category.category_name %></td>
      <td><%= single_post.event.event_name %></td>
      <td><%= single_post.name %></td>
      <td><%= single_post.subject %></td>
      <td><%= single_post.content %></td>
      <%= link_to "詳しく見る", single_posts_user_show_path(single_post.id) %>
    </tr>
<% end %>


<li>
    <%= link_to "topページへ", core_pages_top_path %>
</li>

app/views/single_posts/user_show.html.erb
userが見る単発おもちゃshow


<tr>
      <td><%= @single_post.single_post_image %></td>
      <td><%= @single_post.category.category_name %></td>
      <td><%= @single_post.event.event_name %></td>
      <td><%= @single_post.name %></td>
      <td><%= @single_post.subject %></td>
      <td><%= @single_post.content %></td>
</tr>


<li>
    <%= link_to "userが見る単発投稿index", single_posts_user_index_path %>
</li>